/**
 * Canonical Error Code Enum
 *
 * AUTO-GENERATED from docs/error-codes.yaml
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * To add or modify error codes:
 * 1. Edit docs/error-codes.yaml
 * 2. Run: npm run error-codes:generate
 *
 * @module errors/codes
 */

export const ErrorCode = {
  /** The request is malformed, missing required input, or otherwise invalid */
  BAD_REQUEST: "BAD_REQUEST",

  /** Authentication is missing, malformed, or invalid */
  UNAUTHORIZED: "UNAUTHORIZED",

  /** The caller is authenticated but not allowed to perform the action */
  FORBIDDEN: "FORBIDDEN",

  /** The requested resource does not exist */
  NOT_FOUND: "NOT_FOUND",

  /** The caller has insufficient balance or payment is otherwise required */
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",

  /** The caller exceeded a rate limit */
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

  /** The request conflicts with existing state */
  CONFLICT: "CONFLICT",

  /** An internal service or invariant failed */
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  /** The gateway could not obtain a valid upstream or dependency response */
  BAD_GATEWAY: "BAD_GATEWAY",

  /** A dependency or service is temporarily unavailable */
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  /** A dependency or upstream service did not respond before its timeout */
  GATEWAY_TIMEOUT: "GATEWAY_TIMEOUT",

  /** Request validation failed due to invalid input */
  VALIDATION_ERROR: "VALIDATION_ERROR",

  /** Request body is invalid or malformed */
  INVALID_BODY: "INVALID_BODY",

  /** Query parameters are invalid */
  INVALID_QUERY: "INVALID_QUERY",

  /** URL parameters are invalid */
  INVALID_PARAMS: "INVALID_PARAMS",

  /** A specific field contains an invalid value */
  INVALID_VALUE: "INVALID_VALUE",

  /** Gateway authentication context is unexpectedly missing after auth middleware */
  GATEWAY_AUTH_CONTEXT_MISSING: "GATEWAY_AUTH_CONTEXT_MISSING",

  /** Resolved upstream target fails validation or allowlist checks */
  UPSTREAM_TARGET_BLOCKED: "UPSTREAM_TARGET_BLOCKED",

  /** On-chain or pre-flight balance is too low */
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",

  /** The Soroban RPC request timed out or was aborted */
  SOROBAN_RPC_TIMEOUT: "SOROBAN_RPC_TIMEOUT",

  /** The contract rejected the call, simulation failed, or network error occurred */
  SOROBAN_RPC_ERROR: "SOROBAN_RPC_ERROR",

  /** Billing deduction operation failed */
  BILLING_DEDUCTION_FAILED: "BILLING_DEDUCTION_FAILED",

  /** The requested billing record was not found */
  BILLING_REQUEST_NOT_FOUND: "BILLING_REQUEST_NOT_FOUND",

  /** Developer profile not found */
  DEVELOPER_NOT_FOUND: "DEVELOPER_NOT_FOUND",

  /** Access to the API is forbidden for this developer */
  API_ACCESS_FORBIDDEN: "API_ACCESS_FORBIDDEN",

  /** API key not found */
  API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",

  /** API key is not authorized for this operation */
  API_KEY_FORBIDDEN: "API_KEY_FORBIDDEN",

  /** Refresh token is missing from the request */
  MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",

  /** Refresh token is invalid or malformed */
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",

  /** The token has been revoked */
  REVOKED_TOKEN: "REVOKED_TOKEN",

  /** The token has expired */
  EXPIRED_TOKEN: "EXPIRED_TOKEN",

  /** Token refresh operation failed */
  REFRESH_FAILED: "REFRESH_FAILED",

  /** Token revocation operation failed */
  REVOKE_FAILED: "REVOKE_FAILED",

  /** User is not authenticated */
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",

  /** Failed to retrieve token information */
  TOKEN_INFO_FAILED: "TOKEN_INFO_FAILED",

  /** Vault account not found */
  VAULT_NOT_FOUND: "VAULT_NOT_FOUND",

  /** Failed to retrieve vault balance */
  VAULT_BALANCE_RETRIEVAL_FAILED: "VAULT_BALANCE_RETRIEVAL_FAILED",

  /** Amount parameter is missing */
  MISSING_AMOUNT: "MISSING_AMOUNT",

  /** Amount has invalid type */
  INVALID_AMOUNT_TYPE: "INVALID_AMOUNT_TYPE",

  /** Amount has invalid format */
  INVALID_AMOUNT_FORMAT: "INVALID_AMOUNT_FORMAT",

  /** Network parameter is invalid */
  INVALID_NETWORK: "INVALID_NETWORK",

  /** Network mismatch between request and resource */
  NETWORK_MISMATCH: "NETWORK_MISMATCH",

  /** Source account is invalid */
  INVALID_SOURCE_ACCOUNT: "INVALID_SOURCE_ACCOUNT",

  /** Transaction input is invalid */
  INVALID_TRANSACTION_INPUT: "INVALID_TRANSACTION_INPUT",

  /** Source account not found */
  SOURCE_ACCOUNT_NOT_FOUND: "SOURCE_ACCOUNT_NOT_FOUND",

  /** Contract ID is invalid */
  INVALID_CONTRACT_ID: "INVALID_CONTRACT_ID",

  /** Network is unavailable */
  NETWORK_UNAVAILABLE: "NETWORK_UNAVAILABLE",

  /** Failed to build transaction */
  TRANSACTION_BUILD_FAILED: "TRANSACTION_BUILD_FAILED",

  /** Internal error occurred during vault operation */
  INTERNAL_ERROR: "INTERNAL_ERROR",

  /** Webhook registration is invalid */
  INVALID_WEBHOOK_REGISTRATION: "INVALID_WEBHOOK_REGISTRATION",

  /** Webhook event types are invalid */
  INVALID_WEBHOOK_EVENT_TYPES: "INVALID_WEBHOOK_EVENT_TYPES",

  /** Webhook not found */
  WEBHOOK_NOT_FOUND: "WEBHOOK_NOT_FOUND",

  /** Webhook URL is invalid */
  INVALID_WEBHOOK_URL: "INVALID_WEBHOOK_URL",

  /** Webhook URL validation failed */
  WEBHOOK_URL_VALIDATION_FAILED: "WEBHOOK_URL_VALIDATION_FAILED",

  /** Webhook signature headers are missing */
  MISSING_WEBHOOK_SIGNATURE_HEADERS: "MISSING_WEBHOOK_SIGNATURE_HEADERS",

  /** Webhook timestamp is invalid */
  INVALID_WEBHOOK_TIMESTAMP: "INVALID_WEBHOOK_TIMESTAMP",

  /** Webhook timestamp is outside acceptable window */
  WEBHOOK_TIMESTAMP_OUT_OF_WINDOW: "WEBHOOK_TIMESTAMP_OUT_OF_WINDOW",

  /** Webhook signature is malformed */
  MALFORMED_WEBHOOK_SIGNATURE: "MALFORMED_WEBHOOK_SIGNATURE",

  /** Webhook signature verification failed */
  INVALID_WEBHOOK_SIGNATURE: "INVALID_WEBHOOK_SIGNATURE",

  /** IP address format is invalid */
  INVALID_IP_FORMAT: "INVALID_IP_FORMAT",

  /** IP address is not in the allowlist */
  IP_NOT_ALLOWED: "IP_NOT_ALLOWED",

  /** Database is not available */
  DATABASE_NOT_AVAILABLE: "DATABASE_NOT_AVAILABLE",

  /** Idempotency key conflict with different request */
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",

  /** Request with this idempotency key is still in progress */
  IDEMPOTENCY_IN_PROGRESS: "IDEMPOTENCY_IN_PROGRESS",

  /** Soroban simulation failed */
  SIMULATION_FAILED: "SIMULATION_FAILED",

  /** Authorization header is invalid */
  INVALID_AUTH_HEADER: "INVALID_AUTH_HEADER",

  /** Authentication token is missing */
  MISSING_TOKEN: "MISSING_TOKEN",

  /** Authentication token is invalid */
  INVALID_TOKEN: "INVALID_TOKEN",

  /** Token claims are missing */
  MISSING_CLAIMS: "MISSING_CLAIMS",

  /** Authentication token has expired */
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  /** Authentication token is not yet active */
  TOKEN_NOT_ACTIVE: "TOKEN_NOT_ACTIVE",

  /** Quota request not found */
  QUOTA_REQUEST_NOT_FOUND: "QUOTA_REQUEST_NOT_FOUND",

  /** Quota request has already been resolved */
  QUOTA_REQUEST_ALREADY_RESOLVED: "QUOTA_REQUEST_ALREADY_RESOLVED",

  /** Quota request is invalid */
  INVALID_QUOTA_REQUEST: "INVALID_QUOTA_REQUEST",

  /** Request timeout */
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",

  /** Request body exceeds size limit */
  REQUEST_BODY_TOO_LARGE: "REQUEST_BODY_TOO_LARGE",

  /** Media type is not supported */
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",

  /** Request is syntactically correct but semantically invalid */
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY"

} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * Type guard to check if a value is a valid ErrorCode
 * @param value - Value to check
 * @returns True if value is a valid error code
 */
export function isErrorCode(value: unknown): value is ErrorCode {
  if (typeof value !== "string") return false;
  return Object.values(ErrorCode).includes(value as ErrorCode);
}
