/**
 * Canonical, typed error code catalog.
 *
 * This file exists to ensure there is a single source of truth for every
 * machine-readable error code emitted by the backend.
 */

export const ErrorCode = {
  // HTTP status derived / base app codes
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  CONFLICT: "CONFLICT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_GATEWAY: "BAD_GATEWAY",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  GATEWAY_TIMEOUT: "GATEWAY_TIMEOUT",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_BODY: "INVALID_BODY",
  INVALID_QUERY: "INVALID_QUERY",
  INVALID_PARAMS: "INVALID_PARAMS",
  INVALID_VALUE: "INVALID_VALUE",

  // Gateway / proxy
  GATEWAY_AUTH_CONTEXT_MISSING: "GATEWAY_AUTH_CONTEXT_MISSING",
  UPSTREAM_TARGET_BLOCKED: "UPSTREAM_TARGET_BLOCKED",

  // Billing / Soroban
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  SOROBAN_RPC_TIMEOUT: "SOROBAN_RPC_TIMEOUT",
  SOROBAN_RPC_ERROR: "SOROBAN_RPC_ERROR",
  BILLING_DEDUCTION_FAILED: "BILLING_DEDUCTION_FAILED",

  // Billing request
  BILLING_REQUEST_NOT_FOUND: "BILLING_REQUEST_NOT_FOUND",

  // Developer / API keys
  DEVELOPER_NOT_FOUND: "DEVELOPER_NOT_FOUND",
  API_ACCESS_FORBIDDEN: "API_ACCESS_FORBIDDEN",
  API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",
  API_KEY_FORBIDDEN: "API_KEY_FORBIDDEN",

  // Refresh-token auth
  MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REVOKED_TOKEN: "REVOKED_TOKEN",
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  REFRESH_FAILED: "REFRESH_FAILED",
  REVOKE_FAILED: "REVOKE_FAILED",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  TOKEN_INFO_FAILED: "TOKEN_INFO_FAILED",

  // Vault / deposit
  VAULT_NOT_FOUND: "VAULT_NOT_FOUND",
  VAULT_BALANCE_RETRIEVAL_FAILED: "VAULT_BALANCE_RETRIEVAL_FAILED",
  MISSING_AMOUNT: "MISSING_AMOUNT",
  INVALID_AMOUNT_TYPE: "INVALID_AMOUNT_TYPE",
  INVALID_AMOUNT_FORMAT: "INVALID_AMOUNT_FORMAT",
  INVALID_NETWORK: "INVALID_NETWORK",
  NETWORK_MISMATCH: "NETWORK_MISMATCH",
  INVALID_SOURCE_ACCOUNT: "INVALID_SOURCE_ACCOUNT",
  INVALID_TRANSACTION_INPUT: "INVALID_TRANSACTION_INPUT",
  SOURCE_ACCOUNT_NOT_FOUND: "SOURCE_ACCOUNT_NOT_FOUND",
  INVALID_CONTRACT_ID: "INVALID_CONTRACT_ID",
  NETWORK_UNAVAILABLE: "NETWORK_UNAVAILABLE",
  TRANSACTION_BUILD_FAILED: "TRANSACTION_BUILD_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Webhooks
  INVALID_WEBHOOK_REGISTRATION: "INVALID_WEBHOOK_REGISTRATION",
  INVALID_WEBHOOK_EVENT_TYPES: "INVALID_WEBHOOK_EVENT_TYPES",
  WEBHOOK_NOT_FOUND: "WEBHOOK_NOT_FOUND",
  INVALID_WEBHOOK_URL: "INVALID_WEBHOOK_URL",
  WEBHOOK_URL_VALIDATION_FAILED: "WEBHOOK_URL_VALIDATION_FAILED",
  MISSING_WEBHOOK_SIGNATURE_HEADERS: "MISSING_WEBHOOK_SIGNATURE_HEADERS",
  INVALID_WEBHOOK_TIMESTAMP: "INVALID_WEBHOOK_TIMESTAMP",
  WEBHOOK_TIMESTAMP_OUT_OF_WINDOW: "WEBHOOK_TIMESTAMP_OUT_OF_WINDOW",
  MALFORMED_WEBHOOK_SIGNATURE: "MALFORMED_WEBHOOK_SIGNATURE",
  INVALID_WEBHOOK_SIGNATURE: "INVALID_WEBHOOK_SIGNATURE",

  // IP allowlist
  INVALID_IP_FORMAT: "INVALID_IP_FORMAT",
  IP_NOT_ALLOWED: "IP_NOT_ALLOWED",

  // DB / infrastructure
  DATABASE_NOT_AVAILABLE: "DATABASE_NOT_AVAILABLE",

  // Idempotency
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  IDEMPOTENCY_IN_PROGRESS: "IDEMPOTENCY_IN_PROGRESS",

  // Misc / direct middleware responses
  SIMULATION_FAILED: "SIMULATION_FAILED",

  // Route-specific / auth overrides (documented in docs/error-codes.md)
  INVALID_AUTH_HEADER: "INVALID_AUTH_HEADER",
  MISSING_TOKEN: "MISSING_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  MISSING_CLAIMS: "MISSING_CLAIMS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_NOT_ACTIVE: "TOKEN_NOT_ACTIVE",

  // Quota self-service
  QUOTA_REQUEST_NOT_FOUND: "QUOTA_REQUEST_NOT_FOUND",
  QUOTA_REQUEST_ALREADY_RESOLVED: "QUOTA_REQUEST_ALREADY_RESOLVED",
  INVALID_QUOTA_REQUEST: "INVALID_QUOTA_REQUEST",

  // HTTP fallback derived codes referenced by documentation
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  REQUEST_BODY_TOO_LARGE: "REQUEST_BODY_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export function isErrorCode(value: unknown): value is ErrorCode {
  if (typeof value !== "string") return false;
  return Object.values(ErrorCode).includes(value as ErrorCode);
}
